In [1]:
import numpy as np

In [3]:
# Sıfırdan array tanımlamak
my_list_1 = [5,18,"Furkan",True,45.876,98,-3]
my_array_1 = np.array([5,18,"Furkan",True,45.876,98,-3])

print(f"my_list_1 = {my_list_1}")
print(f"my_array_1 = {my_array_1}")
print("-"*50)
print(type(my_list_1))
print(type(my_array_1))

my_list_1 = [5, 18, 'Furkan', True, 45.876, 98, -3]
my_array_1 = ['5' '18' 'Furkan' 'True' '45.876' '98' '-3']
--------------------------------------------------
<class 'list'>
<class 'numpy.ndarray'>


In [7]:
my_array_1 = np.array([5,18,"186",True,45.876,98,-3],dtype=np.int32)
print(my_array_1)

[  5  18 186   1  45  98  -3]


In [17]:
# Numpy ile rastgele bir sayı tanımlamak
print(np.random.randint(5,100))

# Numpy ile birçok rastgele sayı tanımlamak. Örneğin, 8 adet
print(np.random.randint(5,100,8))

81
[29 16 81 25 62 48 67 65]


In [19]:
# Numpy ile 0-1 arasında değer üretmek (2 satır 3 sütun boyunca)
print(np.random.rand(2,3))

[[0.86912732 0.81273247 0.5601673 ]
 [0.64245766 0.20034851 0.65369158]]


In [21]:
# 0'dan 10'a kadar (10 dahil değil) sıralı değerlerle array üretmek
my_array_2 = np.arange(10)
print(my_array_2)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
my_array_3 = np.arange(0,51,5)
print(my_array_3)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [25]:
my_array_4 = np.arange(0.0,0.6,0.1,dtype=np.float32)
print(my_array_4)

[0.  0.1 0.2 0.3 0.4 0.5]


In [27]:
# Numpy ile istenilen aralıkta, istenilen sayıda eşit aralıklarla artan
# sayılar üretmek
# Örneğin, 0 ile 9 arasında 18 eşit parçaya bölen kod

my_array_5 = np.linspace(0,9,18)
print(my_array_5)

[0.         0.52941176 1.05882353 1.58823529 2.11764706 2.64705882
 3.17647059 3.70588235 4.23529412 4.76470588 5.29411765 5.82352941
 6.35294118 6.88235294 7.41176471 7.94117647 8.47058824 9.        ]


In [29]:
# İki boyutlu matrislere giriş

# 0-100 arasında rastgele sayılardan oluşan 3x2 boyutunda matris tanımlama
# 3 satır, 2 sütun => Eleman sayısı = 3*2 = 6

my_array_6 = np.random.randint(0,100,(3,2))
print(my_array_6)

[[32 34]
 [40  9]
 [50 53]]


In [31]:
# Matrislerle ilgili sık kullanılan özellikler

print(f"Matrisin satır ve sütun sayısı = {my_array_6.shape}")
print("-"*50)
print(f"Matrisin satır sayısı = {my_array_6.shape[0]}")
print(f"Matrisin sütun sayısı = {my_array_6.shape[1]}")
print("-"*50)
print(f"Matrisin eleman sayısı = {my_array_6.size}")
print("-"*50)
print(f"Matrisin boyutu = {my_array_6.ndim}")

Matrisin satır ve sütun sayısı = (3, 2)
--------------------------------------------------
Matrisin satır sayısı = 3
Matrisin sütun sayısı = 2
--------------------------------------------------
Matrisin eleman sayısı = 6
--------------------------------------------------
Matrisin boyutu = 2


In [33]:
my_array_7 = np.random.randint(0,100,(5,4))

print(f"Matrisle ilgili istatistiksel bilgiler")
print(f"En küçük eleman = {np.min(my_array_7)}")
print(f"En büyük eleman = {np.max(my_array_7)}")
print(f"Elemanların ortalama değeri = {np.mean(my_array_7)}")
print(f"En küçük elemanın indeks değeri = {np.argmin(my_array_7)}")
print(f"En büyük elemanın indeks değeri = {np.argmax(my_array_7)}")
print(f"Matrisin standart sapma değeri = {np.std(my_array_7)}")
print(f"Matrisin medyanı (ortanca değeri) = {np.median(my_array_7)}")

Matrisle ilgili istatistiksel bilgiler
En küçük eleman = 1
En büyük eleman = 99
Elemanların ortalama değeri = 46.35
En küçük elemanın indeks değeri = 3
En büyük elemanın indeks değeri = 19
Matrisin standart sapma değeri = 31.659556219252348
Matrisin medyanı (ortanca değeri) = 41.5


In [35]:
my_array_7

array([[ 9, 84, 62,  1],
       [87, 72, 77, 28],
       [35, 71, 62, 13],
       [ 7, 23, 23, 13],
       [92, 48, 21, 99]])

In [57]:
print(my_array_7)
# Matrisin kendi içinde toplanması
print(f"Tüm matrisin toplam değeri = {np.sum(my_array_7)}")
print(f"Sadece Sütun değerlerinin toplanması = {np.sum(my_array_7,axis=0)}")
print(f"Sadece Satır değerlerinin toplanması = {np.sum(my_array_7,axis=1)}")

[[ 1  7  9 13]
 [13 21 23 23]
 [28 35 48 62]
 [62 71 72 77]
 [84 87 92 99]]
Tüm matrisin toplam değeri = 927
Sadece Sütun değerlerinin toplanması = [188 221 244 274]
Sadece Satır değerlerinin toplanması = [ 30  80 173 282 362]


In [59]:
# Özel matris üretmek

# İçi sadece sıfır (0) değeriyle dolu olan matris üretmek (istenilen boyutta)
my_array_8 = np.zeros((3,4))

# İçi sadece bir (0) değeriyle dolu olan matris üretmek (istenilen boyutta)
my_array_9 = np.ones((2,5))

# İçi tamamen sizin verdiğiniz değerlerle dolu olan matris (istenilen boyutta)
my_array_10 = np.full((3,3),12)

# Diyagonal matris (satır ve sütun sayısı eşit olan yerlerde 1, diğerlerinde)
# 0 değeri ile dolu olan matris
my_array_11 = np.eye(5)

In [61]:
print(f"Sıfırlarla dolu matris = {my_array_8}")
print(f"-"*50)
print(f"Birlerle dolu matris = {my_array_9}")
print(f"-"*50)
print(f"İstenilen değerlerle dolu matris = {my_array_10}")
print(f"-"*50)
print(f"Diyagonal matris = {my_array_11}")
print(f"-"*50)

Sıfırlarla dolu matris = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------------------------------------
Birlerle dolu matris = [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
--------------------------------------------------
İstenilen değerlerle dolu matris = [[12 12 12]
 [12 12 12]
 [12 12 12]]
--------------------------------------------------
Diyagonal matris = [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
--------------------------------------------------


In [65]:
# Bir matris ile skalar bir değeri matematiksel işleme sokabilirsiniz
# yani bir matris ile bir int tipindeki değeri toplayabilirsiniz

my_array_12 = np.random.randint(1,10,(2,2))

print(my_array_12)
print("-"*50)
print(my_array_12+4)

[[6 2]
 [5 5]]
--------------------------------------------------
[[10  6]
 [ 9  9]]


In [69]:
# her ikisi de 1 ile 100 değeri arasındaki rastgele değerlerden oluşan
# 3x3 matris tanımlayınız

my_array_13 = np.random.randint(0,100,(3,3))
my_array_14 = np.random.randint(0,100,(3,3))

print(my_array_13)
print("-"*50)
print(my_array_14)

# Bu iki matris arasında 4 temel matematiksel işlemi yapınız
print(f"Matrislerin Toplamı = {my_array_13+my_array_14}")
print("-"*50)
print(f"Matrislerin Farkı = {my_array_13-my_array_14}")
print("-"*50)
print(f"Matrislerin Çarpımı = {my_array_13*my_array_14}")
print("-"*50)
print(f"Matrislerin Bölümü = {my_array_13/my_array_14}")
print("-"*50)
# Ayrıca, bu matrislerin değerlerinin karesini alınız
print(f"1. Matrisin karesi = {my_array_13**2}")
print("-"*50)
print(f"2. Matrisin karesi = {my_array_14**2}")
print("-"*50)
# Son olarak her iki matristede yer alan tek sayıları gösteriniz
print(f"1. Matristeki Tek sayılar = {my_array_13%2!=0}")
print("-"*50)
print(f"2. Matristeki Tek sayılar = {my_array_14%2!=0}")

[[36 20 21]
 [93 77  4]
 [21 85 61]]
--------------------------------------------------
[[ 8 97 18]
 [29 57 53]
 [36 22 36]]
Matrislerin Toplamı = [[ 44 117  39]
 [122 134  57]
 [ 57 107  97]]
--------------------------------------------------
Matrislerin Farkı = [[ 28 -77   3]
 [ 64  20 -49]
 [-15  63  25]]
--------------------------------------------------
Matrislerin Çarpımı = [[ 288 1940  378]
 [2697 4389  212]
 [ 756 1870 2196]]
--------------------------------------------------
Matrislerin Bölümü = [[4.5        0.20618557 1.16666667]
 [3.20689655 1.35087719 0.0754717 ]
 [0.58333333 3.86363636 1.69444444]]
--------------------------------------------------
1. Matrisin karesi = [[1296  400  441]
 [8649 5929   16]
 [ 441 7225 3721]]
--------------------------------------------------
2. Matrisin karesi = [[  64 9409  324]
 [ 841 3249 2809]
 [1296  484 1296]]
--------------------------------------------------
1. Matristeki Tek sayılar = [[False False  True]
 [ True  True False]
 [ Tru

In [73]:
# Bir numpy array içerisinde istenilen koşulu sağlayan elemanları bulma

my_array_15 = np.random.randint(0,100,(6,6))

# Array içerisindeki tek sayıların indeksleri
my_index_15 = np.where(my_array_15%2!=0)

# Array içerisindeki tek sayılar
my_values_15 = my_array_15[my_index_15]
#my_array_15[satır][sütun]

print(f"Orijinal Array = {my_array_15}")
print("-"*50)
print(f"İndeksler = {my_index_15}")
print("-"*50)
print(f"Değerler = {my_values_15}")
print(f"Toplam eleman = {my_values_15.size}")

Orijinal Array = [[16 40 30  1 40 12]
 [36 10 53 60 17  4]
 [42  4 42 63 21 37]
 [57 17 10 34 25  7]
 [ 4 69  4  4 75 47]
 [75 15 15 18 13 76]]
--------------------------------------------------
İndeksler = (array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5], dtype=int64), array([3, 2, 4, 3, 4, 5, 0, 1, 4, 5, 1, 4, 5, 0, 1, 2, 4], dtype=int64))
--------------------------------------------------
Değerler = [ 1 53 17 63 21 37 57 17 25  7 69 75 47 75 15 15 13]
Toplam eleman = 17


In [79]:
# 4x4 boyutunda 50 ile 100 arasında rastgele değerlerden oluşan bir matris
# tanımlayın
my_array_16 = np.random.randint(50,100,(4,4))

print(f"my_array_16 = {my_array_16}")
print("-"*50)
# Bu matristeki 75'ten büyük çift sayıları getiren kodu yazın
my_conditional_16 = (my_array_16>75) & (my_array_16%2==0)
my_index_16 = np.where(my_conditional_16)
print(f"Koşulu sağlayan değerler = {my_array_16[my_index_16]}")

my_array_16 = [[71 57 77 82]
 [56 92 74 86]
 [70 62 56 92]
 [78 85 56 96]]
--------------------------------------------------
Koşulu sağlayan değerler = [82 92 86 92 78 96]


In [89]:
# Array'leri birleştirme

# 2 metot kullanılır
# tek boyutlu array olarak birleştirmek için concatenate

my_array_17 = np.array([1, 2, 3])
my_array_18 = np.array([11, 12, 13])
#deneme = np.array([21, 22, 23])
my_array_19_concat = np.concatenate((my_array_17, my_array_18))

# Array'leri olduğu gibi alt alta birleştirmek için stack
my_array_20_stack = np.stack((my_array_17, my_array_18))

print(f"Matris_1 = {my_array_17}")
print(f"Matris_2 = {my_array_18}")
print("-"*50)
print(f"Concat ile birleştirme = {my_array_19_concat}")
print("-"*50)
print(f"Stack ile birleştirme = {my_array_20_stack}")

Matris_1 = [1 2 3]
Matris_2 = [11 12 13]
--------------------------------------------------
Concat ile birleştirme = [ 1  2  3 11 12 13]
--------------------------------------------------
Stack ile birleştirme = [[ 1  2  3]
 [11 12 13]]


In [91]:
my_array_20 = np.array([1, 2, 2, -4, 5 ,98, 103, 16, -16, 32, 2, -4])
print(f"orijinal Array = {my_array_20}")
print("-"*20)
my_array_21_unique = np.unique(my_array_20)

print(f"Yeni Array = {my_array_21_unique}")
# yukarıdaki my_array_20'yi manuel olarak ( yani np.unique() kullanmadan)
# Önce tekrar eden değerlerden kurtulun
# sonra da bu değerleri sıralayın
# Son kertede sıralanmış verileri bir değişkene aktarın
# bu değişkeni ve tipini yazdırın (tipi numpy.ndarray olmalı!!!)


orijinal Array = [  1   2   2  -4   5  98 103  16 -16  32   2  -4]
--------------------
Yeni Array = [-16  -4   1   2   5  16  32  98 103]


In [93]:
# Aşama_1, tekrar eden verilerden kurtulma
my_set_1 = set(my_array_20)
print(f"Orijinal Array = {my_array_20}")
print(f"Yeni Değerler = {my_set_1}")

Orijinal Array = [  1   2   2  -4   5  98 103  16 -16  32   2  -4]
Yeni Değerler = {32, 1, 2, 98, 5, 103, 16, -16, -4}


In [97]:
# Aşama_2, Verilerin sıralı hale getirilmesi
my_array_sirali = np.array(sorted(my_set_1))
print(my_array_sirali)
print(type(my_array_sirali))

[-16  -4   1   2   5  16  32  98 103]
<class 'numpy.ndarray'>


In [109]:
# Array içerisinde istenilen aralıkta olmayan değerleri bizim verdiğimiz
# değerlerle değiştiren metot

my_array_22 = np.array([15,38,4500,180,-58,0,29,45,49,1,18,-1200])
print(f"Orijinal Array = {my_array_22}")
print("-"*50)

my_array_23_clip = np.clip(my_array_22,20,100)
print(f"İşlenmiş Array = {my_array_23_clip}")

# Alt limit 40
# Üst limit array'in ortalama değeri

my_array_24_clip = np.clip(my_array_22,40,np.mean(my_array_22))
print("-"*50)
print(f"Yeni İşlenmiş Array (mean) = {my_array_24_clip}")

Orijinal Array = [   15    38  4500   180   -58     0    29    45    49     1    18 -1200]
--------------------------------------------------
İşlenmiş Array = [ 20  38 100 100  20  20  29  45  49  20  20  20]
--------------------------------------------------
Yeni İşlenmiş Array (mean) = [ 40.          40.         301.41666667 180.          40.
  40.          40.          45.          49.          40.
  40.          40.        ]
